# Generated by Django 4.2.16 on 2025-02-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0024_alter_userprofile_language"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("basic_access", "Can access this app"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WandererManagedMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wanderer_url",
                    models.CharField(
                        help_text="URL of the wanderer instance", max_length=120
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Map slug on the wanderer instance", max_length=20
                    ),
                ),
                (
                    "map_api_key",
                    models.CharField(help_text="API key of the map", max_length=100),
                ),
                (
                    "map_acl_id",
                    models.CharField(
                        help_text="ID of the managed access list", max_length=100
                    ),
                ),
                ("map_acl_api_key", models.CharField(max_length=100)),
                (
                    "alliance_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Alliances to whose members this server is available.",
                        to="eveonline.eveallianceinfo",
                    ),
                ),
                (
                    "character_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters to which this server is available.",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "corporation_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Corporations to whose members this server is available.",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "group_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups to whose members this server is available.",
                        to="auth.group",
                    ),
                ),
                (
                    "state_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="States to whose members this server is available.",
                        to="authentication.state",
                    ),
                ),
            ],
        ),
    ]
