# Generated by Django 4.2.16 on 2025-02-17 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wanderer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wanderermanagedmap",
            old_name="slug",
            new_name="map_slug",
        ),
    ]
