# Generated by Django 4.2.28 on 2026-09-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanderer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderermanagedmap',
            name='sync_structures',
            field=models.BooleanField(default=False, help_text='Enable hourly structure sync for this map'),
        ),
        migrations.CreateModel(
            name='MapStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanderer_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('structure_type', models.CharField(blank=True, max_length=100)),
                ('structure_type_id', models.CharField(blank=True, max_length=50)),
                ('solar_system_id', models.BigIntegerField(blank=True, null=True)),
                ('solar_system_name', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_ticker', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='wanderer.wanderermanagedmap')),
            ],
            options={
                'ordering': ['map__name', 'solar_system_name', 'name'],
            },
        ),
    ]
