# Generated by Django 4.2.16 on 2025-02-18 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wanderer", "0002_rename_slug_wanderermanagedmap_map_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="WandererUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Auth user linked to the map",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wanderer_map",
                    models.ForeignKey(
                        help_text="Wanderer map to which the user is linked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wanderer.wanderermanagedmap",
                    ),
                ),
            ],
        ),
    ]
