# Generated by Django 4.2.16 on 2025-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanderer", "0003_wandereruser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="map_acl_api_key",
            field=models.CharField(
                help_text="API key of the managed access list", max_length=100
            ),
        ),
    ]
