# Generated by Django 4.2.16 on 2025-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanderer", "0004_alter_wanderermanagedmap_map_acl_api_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wandereruser",
            constraint=models.UniqueConstraint(
                fields=("user", "wanderer_map"), name="functional_pk_user_map"
            ),
        ),
    ]
