# Generated by Django 4.2.16 on 2025-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanderer", "0005_wandereruser_functional_pk_user_map"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wanderermanagedmap",
            constraint=models.UniqueConstraint(
                fields=("wanderer_url", "map_slug"), name="functional_pk_urlslug"
            ),
        ),
    ]
