# Generated by Django 4.2.16 on 2025-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0024_alter_userprofile_language"),
        ("wanderer", "0006_wanderermanagedmap_functional_pk_urlslug"),
    ]

    operations = [
        migrations.AddField(
            model_name="wanderermanagedmap",
            name="faction_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Factions to whose members this map is available.",
                to="eveonline.evefactioninfo",
            ),
        ),
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="alliance_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Alliances to whose members this map is available.",
                to="eveonline.eveallianceinfo",
            ),
        ),
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="character_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Characters to which this map is available.",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="corporation_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Corporations to whose members this map is available.",
                to="eveonline.evecorporationinfo",
            ),
        ),
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="group_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups to whose members this map is available.",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="wanderermanagedmap",
            name="state_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="States to whose members this map is available.",
                to="authentication.state",
            ),
        ),
    ]
