# Generated by Django 4.2.16 on 2025-03-04 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wanderer", "0007_wanderermanagedmap_faction_access_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WandererUser",
            new_name="WandererAccount",
        ),
    ]
