# Generated by Django 4.2.16 on 2025-03-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanderer", "0008_rename_wandereruser_wandereraccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wandereraccount",
            name="wanderer_map",
            field=models.ForeignKey(
                help_text="Wanderer map to which the user is linked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                related_query_name="account",
                to="wanderer.wanderermanagedmap",
            ),
        ),
    ]
