# Generated by Django 4.2.16 on 2025-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanderer", "0009_alter_wandereraccount_wanderer_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="wanderermanagedmap",
            name="name",
            field=models.CharField(
                default="Temp name",
                help_text="User friendly name for your users to recognize the map",
                max_length=80,
            ),
            preserve_default=False,
        ),
    ]
