# Generated by Django 4.2.28 on 2026-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderer', '0009_structurefilterpreset_filter_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapstructure',
            options={'ordering': ['map__name', 'solar_system__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['-last_seen_at', 'solar_system__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='structurefilterpreset',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='structurefilterpreset',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first in the preset list.'),
        ),
    ]
