stages:
  - checks
  - test
  - deploy

pre-commit:
  stage: checks
  image: python:3.10-bookworm
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - apt-get update
    - apt-get install gettext -y
  script:
    - pip install pre-commit
    - pre-commit run --all-files

pylint:
  stage: checks
  extends: .tox_setup
  image: python:3.10-bookworm
  script:
  - tox -e pylint

.tox_setup:
  before_script:
    - apt-get update
    - apt-get install redis-server -y
    - redis-server --daemonize yes
    - python -V
    - pip install tox

test-py310-dj42:
  extends: .tox_setup
  image: python:3.10-bookworm
  script:
    - tox -e py310-django42

test-py311-dj42:
  extends: .tox_setup
  image: python:3.11-bookworm
  script:
    - tox -e py311-django42

test-py312-dj42:
  extends: .tox_setup
  image: python:3.12-bookworm
  script:
    - tox -e py312-django42

test-py313-dj42:
  extends: .tox_setup
  image: python:3.13-bookworm
  script:
    - tox -e py313-django42

deploy-pypi:
  stage: deploy
  image: python:3.10-bookworm
  before_script:
    - pip install twine wheel build
    - apt update && apt install -y jq

  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script:
    - python -m build
    # Retrieve the OIDC token from GitLab CI/CD, and exchange it for a PyPI API token
    - oidc_token=$(python -m id PYPI)
    - resp=$(curl -X POST https://pypi.org/_/oidc/mint-token -d "{\"token\":\"${oidc_token}\"}")
    - api_token=$(jq --raw-output '.token' <<< "${resp}")

    # Upload to PyPI authenticating via the newly-minted token
    - twine upload -u __token__ -p "${api_token}" dist/*

  rules:
    - if: $CI_COMMIT_TAG
